### ISSUE TITLE
ReferenceError: controllers is not defined

### ISSUE THREAD

**Issue by halbtuerke** [nodeontrain/trainjs#13]
Hi,

I just found out about Node On Train and started the tutorial. After scaffolding the User resource and running the migration the server won't start anymore (it did run before). Here's the error message I got:

```
trainjs server
/usr/local/lib/node_modules/trainjs/lib/train.js:127

                                var class_object = new controllers[routes[k]['resources']]();

                                                       ^



ReferenceError: controllers is not defined

    at /usr/local/lib/node_modules/trainjs/lib/train.js:127:28

    at module.exports (/usr/local/lib/node_modules/trainjs/node_modules/connect-route/lib/connect-route.js:99:35)

    at newServer (/usr/local/lib/node_modules/trainjs/lib/train.js:117:9)

    at Object.<anonymous> (/usr/local/lib/node_modules/trainjs/lib/train.js:176:28)

    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/trainjs/bin/server.js:24:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

Error Code: 1
Exiting
```

Train Version: 2.0.20
Node Version: 5.5.0

Let me know if you need any further information.

**Comment by train255** [comment]
Thank you very much, I fixed it

**Comment by halbtuerke** [comment]
Thanks, now it works. :+1:
